language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - '7'
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
after_success:
  - npm run release
  - npm publish 
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
